Update 03_create-a-branch.md
brasilidade/introduction-to-github pull request #2
Opened 2020-10-22 02:26 UTC by eshinkawa

Pessoal, dêem uma olhada, sugestões são mais que bem vindas.

2020-10-22 12:43 UTC, Koalapvh13 reviewed
Olá @eshinkawa,

A sua tradução está muito boa. Só pontuei algumas passagens em que penso poder ser melhoradas a questão do uso das traduções de termos estrangeiros. Tambem comentei sobre um pequeno erro de digitação e fiz umas sugestões de estética da escrita.

2020-10-22 12:43 UTC, Koalapvh13 commented on responses/pt-br/03_create-a-branch.md
> +1. Abra a interface de linha comando de sua preferência, a qual nós chamaremos de shell (casca) de agora em diante.
Essa tradução para o termo shell ficou um pouco destoante do contexto de Git, na minha opinião. Talvez isso possa causar confusão nos iniciantes que seguirem esse curso. É apenas um ponto de vista. 
```suggestion
1. Abra a interface de linha comando de sua preferência, a qual nós chamaremos de shell a partir de agora.
```

2020-10-22 12:43 UTC, Koalapvh13 commented on responses/pt-br/03_create-a-branch.md
> +1. Selecione e diretório no qual você deseja salvar o repositório e clique em **Choose folder**. Então, abra o diretório selecionado.
```suggestion
1. Selecione o diretório no qual você deseja salvar o repositório e clique em **Choose folder**. Então, abra o diretório selecionado.
```

2020-10-22 12:43 UTC, Koalapvh13 commented on responses/pt-br/03_create-a-branch.md
> +3. No campo, digite um nome para sua branch, por ex. `my-slide`
```suggestion
3. No campo, digite um nome para sua branch, por exemplo, `my-slide`
```

2020-10-22 12:49 UTC, eshinkawa commented on responses/pt-br/03_create-a-branch.md
> +1. Abra a interface de linha comando de sua preferência, a qual nós chamaremos de shell (casca) de agora em diante.
Faz sentido

2020-10-23 01:30 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +Vamos completar o primeiro Github flow (Fluxo do Github): criar uma branch (ramificação) <sup>[:book:](https://help.github.com/articles/github-glossary/#branch)</sup>.
Oi @eshinkawa ! Muito obrigada pela contribuição! 

Desculpa ser a chata (hehe), mas gostaria de sugerir algumas alterações: 
- Github > GitHub (com H maiúsculo)
- Seguindo a [documentação oficial do GitHub em português](https://docs.github.com/pt/free-pro-team@latest/github/getting-started-with-github/github-glossary#branch), `branch` é masculino. Então nesse caso eu sugiro "criar um branch" e o link deve ser esse, que direciona para a versão em português: https://docs.github.com/pt/free-pro-team@latest/github/getting-started-with-github/github-glossary#branch

2020-10-23 01:32 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +<details><summary>Criando uma branch</summary>
Como branch é masculino, aqui deveria ser "Criando um branch"

2020-10-23 01:34 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +Você acabou de aprender como criar uma branch-o primeiro passo no Github flow.
- Aqui também seria "um branch"
- o hífen aqui é, na verdade, um — (mdash, que é mais longo que o hífen). 
- Github > GitHub

2020-10-23 01:37 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +Branches são uma importante parte do GitHub flow porque eles nos permitem separar nossa trabalho da branch `master`.  Em outra palavras, o trabalho de todos está a salvo enquanto você contribui.
Como em português o adjetivo vem depois do substantivo, sugiro alterar

> Branches são uma importante parte

para

> Branches são uma parte importante

----

Outra alteração: 

de 

> permitem separar nossa trabalho da branch `master`.

para

> permitem separar nosso trabalho do branch `main`.

troquei de `master` pra `main` porque o GitHub não vai mais usar o termo `master` 😊 

----

Outra alteração: 

de 

> Em outra palavras, o trabalho de todos está a salvo enquanto você contribui.

para

> Em outras palavras, o trabalho de todos está a salvo enquanto você contribui.

2020-10-23 01:38 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +Um único projeto pode ter centenas de branches, cada uma sugerindo uma nova mudança para a `master` branch.
Alterar o seguinte: 

de 

> Um único projeto pode ter centenas de branches, cada uma sugerindo uma nova mudança para a `master` branch.

para

> Um único projeto pode ter centenas de branches, cada um sugerindo uma nova mudança para a branch `main`.

2020-10-23 01:42 UTC, eshinkawa commented on responses/pt-br/03_create-a-branch.md
> +<details><summary>Criando uma branch</summary>
@eshinkawa eu vou fazer as alterações, mas posso sugerir que as próximas vezes você já faça a sugestão da alteração?

2020-10-23 01:43 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +O melhor jeito de manter branches organizadas com uma equipe é mantê-las concisas e breves. Em outra palavras, uma única branch deve representar uma única funcionalidade o um conserto de bug. Isso di
Seguindo o padrão de que branch é masculino, sugiro alterar

> O melhor jeito de manter branches organizadas com uma equipe é mantê-las concisas e breves.

para

> O melhor jeito de manter branches organizados com uma equipe é mantê-los concisos e breves.

----

Outra alteração: 

de 

> Em outra palavras, uma única branch deve representar uma única funcionalidade o um conserto de bug.

para

> Em outras palavras, um único branch deve representar uma única funcionalidade ou um conserto de bug.

----

Outra alteração:

de 

> Isso diminui a confusão entre contribuidores quando a branch é apenas ativa por alguns poucos dias antes dela ser mergeada <sup>[:book:](https://help.github.com/articles/github-glossary/#merge)</sup> com a branch `master`.

para

> Isso diminui a confusão entre contribuidores quando o branch está ativo apenas por alguns poucos dias antes de ser mergeado <sup>[:book:](https://docs.github.com/pt/free-pro-team@latest/github/getting-started-with-github/github-glossary#merge)</sup> com o branch `main`.

2020-10-23 01:43 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +### :keyboard: Atividade: Sua primeira branch
Seu primeiro branch

2020-10-23 01:44 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Abra a interface de linha comando de sua preferência, a qual nós chamaremos de shell a partir de agora.
De 

> Abra a interface de linha comando de sua preferência,

para

> Abra a interface de linha de comando de sua preferência,

2020-10-23 01:45 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Crie uma branch, de o nome que achar melhor. Sinta-se a vontade de usar o nome sugerido abaixo.
de 

> Crie uma branch, de o nome que achar melhor. Sinta-se a vontade de usar o nome sugerido abaixo.

para

> Crie um branch, dê o nome que achar melhor. Sinta-se à vontade para usar o nome sugerido abaixo.

2020-10-23 01:45 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Dê push na branch para o GitHub:
de 

> Dê push na branch para o GitHub:

para

> Dê push no branch para o GitHub:

2020-10-23 01:55 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. O diretório do repositório deve ser agora aberto no seu projeto do VS Code. Clique em `master` no canto esquerdo da janela do VS Code. Isso vai abrir a Paleta de Comandos referente as branches do
de

> O diretório do repositório deve ser agora aberto no seu projeto do VS Code.

para

> O diretório do repositório agora deve estar aberto no seu projeto do VS Code.

----

de

> Clique em `master` no canto esquerdo da janela do VS Code. Isso vai abrir a Paleta de Comandos referente as branches do Git.

para

> Clique em `main` no canto esquerdo da janela do VS Code. Isso vai abrir a Paleta de Comandos referente aos branches do Git.

2020-10-23 01:55 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +      ![uma captura de tela das branches do Git no VS Code](https://user-images.githubusercontent.com/16547949/53639606-adc76e80-3bf7-11e9-98ac-bd41ae2b40db.png)
de 

> ![uma captura de tela das branches do Git no VS Code]

para

> ![uma captura de tela dos branches do Git no VS Code]

2020-10-23 01:58 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Quando for perguntado para selecionar a ref de origem da branch, selecione `master`.
de 

> Quando for perguntado para selecionar a ref de origem da branch, selecione `master`.

para

> Quando aparecer a solicitação para selecionar a ref de origem do branch, selecione `main`.

este caso é um pouco complicado de traduzir. Com o intuito de manter a diversidade de gênero das pessoas que vão usar este curso, preferi usar "quando aparecer a solicitação...". 

Mas estou aberta, se você tiver uma outra sugestão 😃

2020-10-23 02:00 UTC, eshinkawa commented on responses/pt-br/03_create-a-branch.md
> +1. Quando for perguntado para selecionar a ref de origem da branch, selecione `master`.
@talktopri posso pedir que você sugira a mudança? Acho que fica mais simples

2020-10-23 02:01 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Vá para view de controle de versão, clique na elipse (...) e selecione **Push**. Confirme a caixa de diálogo pedindo para você publicar a branch.
de 

> Vá para view de controle de versão, clique na elipse (...) e selecione **Push**. Confirme a caixa de diálogo pedindo para você publicar a branch.

para

> Clique na opção de controle de versão, clique na elipse (...) e selecione **Push**. Confirme a caixa de diálogo pedindo para você publicar o branch.

2020-10-23 02:01 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +      ![uma captura de tela de view do controle de versão no VS Code](https://user-images.githubusercontent.com/16547949/53640015-ee73b780-3bf8-11e9-8c90-be9022b9555a.png)
de 

> uma captura de tela de view do controle de versão no VS Code

para

> uma captura de tela mostrando o controle de versão no VS Code

2020-10-23 02:02 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +2. Clique em **Branch: master** no drop-down
de 

> Clique em **Branch: master** no drop-down

para

> Clique em **Branch: main** no menu suspenso

2020-10-23 02:02 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +3. No campo, digite um nome para sua branch, por exemplo, `my-slide`
de 

> No campo, digite um nome para sua branch

para

> No campo, digite um nome para seu branch

2020-10-23 02:03 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +4. Clique em **Create branch: <name>** ou pressione a tecla <kbd>Enter</kbd> para criar sua branch
de 

> para criar sua branch

para

> para criar seu branch

2020-10-23 02:03 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +<h3 align="center">Eu vou responder quando detectar que uma branch nova foi criada nesse repositório.</h3>
de

> Eu vou responder quando detectar que uma branch nova foi criada nesse repositório

para

> Eu vou responder quando detectar que um branch novo foi criado nesse repositório

2020-10-23 02:05 UTC, talktopri requested changes
Muito obrigada pela tradução! Este é o primeiro Pull Request deste projeto e eu estou SUPER emocionada ❤️ 

Sei que pedi mil alterações, e espero que você não se importe.
Se tiver qualquer dúvida, estou à disposição 😊

2020-10-23 02:05 UTC, talktopri commented on responses/pt-br/03_create-a-branch.md
> +1. Quando for perguntado para selecionar a ref de origem da branch, selecione `master`.
Acho que pode ser isso aí mesmo então 🤔 
Se ficar estranho a gente arruma depois, hehe

2020-10-23 02:10 UTC, eshinkawa commented
@talktopri segura aí que eu já mando as alterações

2021-09-15 19:07 UTC, closed without merging